In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt


In [2]:
ds=pd.read_csv("Churn_Modelling.csv")
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [3]:
X=ds.iloc[:,3:13]
y=ds.iloc[:,13]
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [4]:
X['Gender']=np.where(X['Gender']=='Female',0,1)
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [5]:
y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [6]:
# from sklearn.preprocessing import OneHotEncoder
# Oh=OneHotEncoder()

temp=pd.get_dummies(ds['Geography'],drop_first=True)
X=pd.concat([X,temp],axis=1)
X

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France       0   42       2       0.00              1   
1             608     Spain       0   41       1   83807.86              1   
2             502    France       0   42       8  159660.80              3   
3             699    France       0   39       1       0.00              2   
4             850     Spain       0   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France       1   39       5       0.00              2   
9996          516    France       1   35      10   57369.61              1   
9997          709    France       0   36       7       0.00              1   
9998          772   Germany       1   42       3   75075.31              2   
9999          792    France       0   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  Germany  Spain  
0             1               1        101348.88        0      0  
1             0               1        112542.58        0      1  
2             1               0        113931.57        0      0  
3             0               0         93826.63        0      0  
4             1               1         79084.10        0      1  
...         ...             ...              ...      ...    ...  
9995          1               0         96270.64        0      0  
9996          1               1        101699.77        0      0  
9997          0               1         42085.58        0      0  
9998          1               0         92888.52        1      0  
9999          1               0         38190.78        0      0  

[10000 rows x 12 columns]

In [7]:
X.drop('Geography',inplace=True,axis=1)
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  
0                  1        101348.88        0      0  
1                  1        112542.58        0      1  
2                  0        113931.57        0      0  
3                  0         93826.63        0      0  
4                  1         79084.10        0      1  
...              ...              ...      ...    ...  
9995               0         96270.64        0      0  
9996               1        101699.77        0      0  
9997               1         42085.58        0      0  
9998               0         92888.52        1      0  
9999               0         38190.78        0      0  

[10000 rows x 11 columns]

In [8]:
X

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619       0   42       2       0.00              1          1   
1             608       0   41       1   83807.86              1          0   
2             502       0   42       8  159660.80              3          1   
3             699       0   39       1       0.00              2          0   
4             850       0   43       2  125510.82              1          1   
...           ...     ...  ...     ...        ...            ...        ...   
9995          771       1   39       5       0.00              2          1   
9996          516       1   35      10   57369.61              1          1   
9997          709       0   36       7       0.00              1          0   
9998          772       1   42       3   75075.31              2          1   
9999          792       0   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Germany  Spain  
0                  1        101348.88        0      0  
1                  1        112542.58        0      1  
2                  0        113931.57        0      0  
3                  0         93826.63        0      0  
4                  1         79084.10        0      1  
...              ...              ...      ...    ...  
9995               0         96270.64        0      0  
9996               1        101699.77        0      0  
9997               1         42085.58        0      0  
9998               0         92888.52        1      0  
9999               0         38190.78        0      0  

[10000 rows x 11 columns]

In [9]:
from sklearn.model_selection import train_test_split
train_X,test_X,train_y,test_y=train_test_split(X,y,random_state=30,test_size=0.30)

In [11]:
from sklearn.preprocessing import StandardScaler
Sc=StandardScaler()

In [12]:
train_X=Sc.fit_transform(train_X)
test_X=Sc.fit_transform(test_X)

In [15]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=100,max_depth=20,max_leaf_nodes=10,max_features='auto')
rf.fit(train_X,train_y)

RandomForestClassifier(max_depth=20, max_leaf_nodes=10)

In [16]:
RFans=rf.predict(test_X)

In [22]:
from sklearn.metrics import accuracy_score
RFScore =accuracy_score(RFans,test_y)*100
RFScore

84.46666666666667

In [23]:
#ANN are build with fully connected layers

from tensorflow.keras.models import Sequential #class
from keras.layers import Dense # class

In [24]:
classifier= Sequential()
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu',input_dim=11)) #units =last layers neuron#
# this will add an input layer and a hidden layer

In [26]:
classifier.add(Dense(units=6,kernel_initializer='uniform',activation='relu')) # one more hidden layer

In [27]:
classifier.add(Dense(units=1,kernel_initializer='uniform',activation='sigmoid')) # Output layer

In [28]:
classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])    #compiling the network

#adam -> performs stoicastic gradeint descent
#loss= used in training  
# binary_crossentropy->for binary classification it calculates the loss predicted labeled and true label
# metrices= for evaluation the network
# accuracy-> total and count(that are used to compute the frequency with y_pred and y_true)

In [29]:
classifier.fit(train_X,train_y,batch_size=10,epochs=100)  

#epoch ->no of times one forward_feed and one backward pass of all the training ex.
#  or no. of times the algorithm will visit the dataset

Epoch 1/100
700/700 [==============================] - 1s 913us/step - loss: 0.4904 - accuracy: 0.8000
Epoch 2/100
700/700 [==============================] - 1s 897us/step - loss: 0.4211 - accuracy: 0.8000
Epoch 3/100
700/700 [==============================] - 1s 949us/step - loss: 0.4135 - accuracy: 0.8181
Epoch 4/100
700/700 [==============================] - 1s 894us/step - loss: 0.4072 - accuracy: 0.8313
Epoch 5/100
700/700 [==============================] - 1s 890us/step - loss: 0.4028 - accuracy: 0.8363
Epoch 6/100
700/700 [==============================] - 1s 885us/step - loss: 0.3997 - accuracy: 0.8416
Epoch 7/100
700/700 [==============================] - 1s 883us/step - loss: 0.3973 - accuracy: 0.8411
Epoch 8/100
700/700 [==============================] - 1s 872us/step - loss: 0.3956 - accuracy: 0.8411
Epoch 9/100
700/700 [==============================] - 1s 944us/step - loss: 0.3939 - accuracy: 0.8426
Epoch 10/100
700/700 [==============================] - 1s 911us/step - l

700/700 [==============================] - 1s 930us/step - loss: 0.3847 - accuracy: 0.8444
Epoch 80/100
700/700 [==============================] - 1s 916us/step - loss: 0.3846 - accuracy: 0.8436
Epoch 81/100
700/700 [==============================] - 1s 936us/step - loss: 0.3844 - accuracy: 0.8444
Epoch 82/100
700/700 [==============================] - 1s 1ms/step - loss: 0.3846 - accuracy: 0.8437
Epoch 83/100
700/700 [==============================] - 1s 1ms/step - loss: 0.3841 - accuracy: 0.8433
Epoch 84/100
700/700 [==============================] - 1s 923us/step - loss: 0.3839 - accuracy: 0.8443
Epoch 85/100
700/700 [==============================] - 1s 883us/step - loss: 0.3832 - accuracy: 0.8436
Epoch 86/100
700/700 [==============================] - 1s 897us/step - loss: 0.3829 - accuracy: 0.8434
Epoch 87/100
700/700 [==============================] - 1s 920us/step - loss: 0.3825 - accuracy: 0.8437
Epoch 88/100
700/700 [==============================] - 1s 911us/step - loss: 0.3

In [30]:
y_pred=classifier.predict(test_X)
y_pred

94/94 [==============================] - 0s 755us/step


array([[0.09102695],
       [0.8409554 ],
       [0.20855257],
       ...,
       [0.07033093],
       [0.12843956],
       [0.23251612]], dtype=float32)

In [31]:
y_pred=(y_pred>0.5)
y_pred

array([[False],
       [ True],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [33]:
from sklearn.metrics import confusion_matrix
CMann=confusion_matrix(test_y,y_pred)
Acann=accuracy_score(test_y,y_pred)

In [34]:
print(CMann)   #     [0,1]-> false predicted incorrect ,  [1,0]-> true predicted incorrect

[[2230  133]
 [ 339  298]]


In [35]:
print(Acann*100)

84.26666666666667


#                          Accuracy

In [45]:
print('\n\tArtifical Neural Network ->',(Acann*100),
      '%\n\tRandom Forest Classifier ->', RFScore,
      '%\n')


	Artifical Neural Network -> 84.26666666666667 %
	Random Forest Classifier -> 84.46666666666667 %

